services:
  - type: web
    name: acydon-scraper-demo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python ingester.py && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
